### ISSUE TITLE
Are digital signatures necessary?

### ISSUE THREAD

**Issue by briansmith** [cedenday/rshare#3]
I saw that the Ed25519 signatures are one-use and the public keys themselves aren't authenticated (IIUC). This make me think it is likely that it would be possible to use an integrity primitive simpler than a signature. I don't have time to investigate this further, and also I might be misunderstanding things, but I think it is something worth looking into. Potentially the protocol could be more valuable in more use cases without the signatures.

**Comment by quininer** [comment]
A signature is necessary, it prevents the server owner (when knowing enckey) to tamper with the file.
but I think using GPG signature is a better choice.

**Comment by cedenday** [comment]
I agree that the signatures are necessary for integrity. The reason I generate a new key pair for every link is to use it for requesting advertisements from peers as seen here: https://github.com/cedenday/rshare/blob/a166b8f6be42b285029c208f860cd81bd49f5827/src/messaging/message.rs#L29 . It also keeps the link size down due to the small size of ed25519 keys.

**Comment by briansmith** [comment]
OK, I'll close this. I think when I filed this issue, I thought the signature was over the entire file, not over the individual parts of the file. if the signature were over the whole file then a hash over the whole thing would be sufficient, but the public key signature is used here so that the recipient could authenticate each individual part.

I don't recommend using GPG signatures.
